schema_version = "1.2"
artifacts = []

[task]
name = "heart-cgp/istio-discovery-server-refac-001"
description = "Rename DiscoveryServer to XDSServer in Istio pilot xds package"
authors = [{ name = "CodeScaleBench" }]
keywords = ["codescalebench", "refactor", "go"]

[metadata]
codescalebench_task_id = "istio-discovery-server-refac-001"
origin_suite = ""
repo = "istio/istio"
category = "cross_file_refactoring"
language = "go"
difficulty = "hard"
source_task_dir = "/home/dylan/CodeScaleBench/benchmarks/csb_sdlc_refactor/istio-discovery-server-refac-001"
selection_rank = 29
verification_command = "bash /tests/test.sh"
verification_reward_type = "checklist"

[verifier]
timeout_sec = 1200.0

[verifier.env]

[agent]
timeout_sec = 1200.0

[environment]
build_timeout_sec = 900.0
os = "linux"
cpus = 4
memory_mb = 8192
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[environment.env]

[solution]

[solution.env]
