schema_version = "1.2"
artifacts = []

[task]
name = "heart-cgp/ansible-abc-imports-fix-001"
description = "ansible-abc-imports-fix-001"
authors = [{ name = "CodeScaleBench" }]
keywords = ["codescalebench", "refactor", ""]

[metadata]
codescalebench_task_id = "ansible-abc-imports-fix-001"
origin_suite = ""
repo = "ansible/ansible"
category = "ccb_swebenchpro"
language = ""
difficulty = ""
source_task_dir = "/home/dylan/CodeScaleBench/benchmarks/csb_sdlc_fix/ansible-abc-imports-fix-001"
selection_rank = 58
verification_command = "bash /tests/test.sh"
verification_reward_type = "test_ratio"

[verifier]
timeout_sec = 600.0

[verifier.env]

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 1800.0
os = "linux"
cpus = 2
memory_mb = 8192
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[environment.env]

[solution]

[solution.env]
