schema_version = "1.2"
artifacts = []

[task]
name = "heart-cgp/pandas-index-engine-refac-001"
description = "Rename _engine property to _index_engine in pandas Index class"
authors = [{ name = "CodeScaleBench" }]
keywords = ["codescalebench", "refactor", "python"]

[metadata]
codescalebench_task_id = "pandas-index-engine-refac-001"
origin_suite = ""
repo = "pandas-dev/pandas"
category = "cross_file_refactoring"
language = "python"
difficulty = "hard"
source_task_dir = "/home/dylan/CodeScaleBench/benchmarks/csb_sdlc_refactor/pandas-index-engine-refac-001"
selection_rank = 34
verification_command = "bash /tests/test.sh"
verification_reward_type = "checklist"

[verifier]
timeout_sec = 1200.0

[verifier.env]

[agent]
timeout_sec = 1200.0

[environment]
build_timeout_sec = 900.0
os = "linux"
cpus = 4
memory_mb = 8192
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[environment.env]

[solution]

[solution.env]
